### ISSUE TITLE
Mac OS Builds

### ISSUE THREAD

**Issue by niwhsa9** [rahulaggarwal965/Love_Calculator_rigged#10]
I've created a sucessful Windows Build. Problem is, it may or may not work on MAC OS. (You will have to try) If not, the problem is most likely the exe file (which is not cross platform). I'll send you instructions on how to make an appropriate exe file that my end can support if needed. Let me know. To download/test the windows version, go to wiki, downloads, and click.

**Comment by rahulaggarwal965** [comment]
I think Ill have to build it cause the jar you provided isnt working.

**Comment by niwhsa9** [comment]
Any luck with freeze? If no, let me know. I got another idea.

**Comment by rahulaggarwal965** [comment]
Ive gotten the loveFinderAlg.app but your peoject.java needs some integration with it. Im working it out.

**Comment by niwhsa9** [comment]
I know, I've got a plan for that. It requires a bit of semi invasive
software but we are good.

On Wednesday, April 6, 2016, rahulaggarwal965 notifications@github.com
wrote:

> Ive gotten the loveFinderAlg.app but your peoject.java needs some
> integration with it. Im working it out.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/rahulaggarwal965/Love_Calculator_rigged/issues/10#issuecomment-206666853

## 

_Ashwin_

**Comment by niwhsa9** [comment]
Rahul, do me a favor, throw your .app into the repo, just in the main directory, I'll move it accordingly.

**Comment by niwhsa9** [comment]
Thanks for the .app push, I'll take care of it now :D
