### ISSUE TITLE
Java/Python code integration 

### ISSUE THREAD

**Issue by niwhsa9** [rahulaggarwal965/Love_Calculator_rigged#5]
We have a very serious problem:
Your code is in python, mines java. LOL! (A clear result of poor planning).
So the way I see it we have two options:

1) User input in java GUI, export to file, invoke python code by calling executable or using Jython, IO file from python, calculate, then export compatibility % back to another file and have java IO back in and display.

2) Port python algorithm to java. 

You choose, way two seems immensely easier to me, I can do it if you tell me to. Otherwise you gotta figure out how you want me to invoke the code from the GUI.

**Comment by rahulaggarwal965** [comment]
Okay, so I'm in San Diego right now so I won't be able to respond for a couple of days but I need you to know: I have created another algorithm that is much more advanced than the previous one with all features such as adding rigged names. However, seeing as I cannot commit and push it right now (I'm writing this message on my iPhone and I only have the code on my computer) I would recommend that you not try to integrate the algorithm right now and instead wait for me to come back from my trip. However, it is your choice if you want to continue and thus we would try to integrate my algorithm later. Thanks, Rahul.

**Comment by rahulaggarwal965** [comment]
One more things, we could try using Django. Just a thought. (I have some experience, not much, so it could be a good learning experience. Your choice.

**Comment by niwhsa9** [comment]
Great, sounds good. I'll wait for you to come home!

On Sun, Apr 3, 2016 at 8:12 PM, rahulaggarwal965 <notifications@github.com>
wrote:

> One more things, we could try using Django. Just a thought. (I have some
> experience, not much, so it could be a good learning experience. Your
> choice.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rahulaggarwal965/Love_Calculator_rigged/issues/5#issuecomment-205114886>
>



-- 
*Ashwin*

**Comment by niwhsa9** [comment]
Great, sounds good. I'll wait for you to come home! Also, enjoy your trip! If you get a chance, check out the java GUI I wrote,
I need to add more stuff to it cuz it looks super bland. If you have any
sugestions let me know. There is a screenshot in the description of what it
looks like.

On Sun, Apr 3, 2016 at 9:06 PM, Ashwin Gupta ashwingupta2000@gmail.com
wrote:

> Great, sounds good. I'll wait for you to come home!
> 
> On Sun, Apr 3, 2016 at 8:12 PM, rahulaggarwal965 <notifications@github.com
> 
> > wrote:
> > 
> > One more things, we could try using Django. Just a thought. (I have some
> > experience, not much, so it could be a good learning experience. Your
> > choice.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/rahulaggarwal965/Love_Calculator_rigged/issues/5#issuecomment-205114886
> 
> ## 
> 
> _Ashwin_

## 

_Ashwin_

**Comment by niwhsa9** [comment]
Okay, I'm going to try using http://cx-freeze.sourceforge.net/ too pacakge your code to EXE and run through java process class. I need you to IO with my files inside my folder called input and output. The way this will work is when the user starts the application it will run Java code. They will enter two names and hit start. The java code will then call your program. When your program starts (**you need to add this in:**), read in from output.txt to get the names of the people, then when it finishes, have it write out to input.txt the percentage compatibility (not including the % sign). Java will then read in from this file to display the precentage compatible. Also, I'll copy over the special messages into a HashMap in java, I'll compute those locally.

**Comment by rahulaggarwal965** [comment]
I did the IO integration with my code.

**Comment by niwhsa9** [comment]
Oh great TY. I'll do my bit tomorrow. You did exactly what I wanted (although you did switch the files, but I'll fix that)!

On Tuesday, April 5, 2016, rahulaggarwal965 notifications@github.com
wrote:

> I did the IO integration with my code.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/rahulaggarwal965/Love_Calculator_rigged/issues/5#issuecomment-206107250

## 

_Ashwin_

**Comment by rahulaggarwal965** [comment]
Cool. Btw you might need to switch input and output for your program, you'll have to see.
