### ISSUE TITLE
Wiki section: code breakdown python

### ISSUE THREAD

**Issue by niwhsa9** [rahulaggarwal965/Love_Calculator_rigged#6]
Rahul, I'm working on the wiki, but I do need your help with one part. I'd like you to contribute to the page "code breakdown"  under the section "Python (Rahul) when you get a chance. Just explain your algorithm, relevant psudeocode, and try to add a bit of comedy. Thanks!

**Comment by rahulaggarwal965** [comment]
Will do.

**Comment by rahulaggarwal965** [comment]
Done.

**Comment by niwhsa9** [comment]
Thanks :D. I'll add my part when I finish writing the GUI...

On Tuesday, April 5, 2016, rahulaggarwal965 notifications@github.com
wrote:

> Done.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/rahulaggarwal965/Love_Calculator_rigged/issues/6#issuecomment-206048711

## 

_Ashwin_
